/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */
package com.yintong.auth.secure;

public final class R {
	public static final class drawable {
		public static final int icon = 0x7f020057;
	}
	public static final class layout {
		public static final int main = 0x7f030029;
	}
	public static final class string {
		public static final int app_name = 0x7f050021;
		public static final int hello = 0x7f050026;
	}
}
